In [9]:
import pandas as pd
import numpy as np

In [10]:
d1=pd.read_csv("rice.csv")
d2=pd.read_csv("wheat.csv")
d3=pd.read_csv("cotton(lint).csv")
d4=pd.read_csv("sugarcane.csv")
d5=pd.read_csv("onion.csv")
d6=pd.read_csv("maize.csv")

In [11]:
d1=d1.dropna()
d2=d2.dropna()
d3=d3.dropna()
d4=d4.dropna()
d5=d5.dropna()
d6=d6.dropna()

In [12]:
d1['Yield']=(d1['Production']*1000)/d1['Area']
d2['Yield']=(d2['Production']*1000)/d2['Area']
d3['Yield']=(d3['Production']*1000)/d3['Area']
d4['Yield']=(d4['Production']*1000)/d4['Area']
d5['Yield']=(d5['Production']*1000)/d5['Area']
d6['Yield']=(d6['Production']*1000)/d6['Area']

In [13]:
def conditions(d):
    if (d['State_Name'] == 'Punjab'):
        return 649
    elif (d['State_Name'] == 'Andhra Pradesh'):
        return 1094
    elif (['State_Name'] == 'Uttar Pradesh'):
        return 1025
    elif (d['State_Name'] == 'Haryana'):
        return 617
    else:
        return 494
        


d1['Rainfall'] = d1.apply(conditions, axis=1)
d2['Rainfall'] = d2.apply(conditions, axis=1)
d3['Rainfall'] = d3.apply(conditions, axis=1)
d4['Rainfall'] = d4.apply(conditions, axis=1)
d5['Rainfall'] = d5.apply(conditions, axis=1)
d6['Rainfall'] = d6.apply(conditions, axis=1)

In [14]:
d1 = d1.drop("Unnamed: 0", axis=1)
d1 = d1.drop("State_Name", axis=1)
d1 = d1.drop("District_Name", axis=1)
d1 = d1.drop("S_No", axis=1)
d1 = d1.drop("pH", axis=1)
d1 = d1.drop("Moisture", axis=1)
d1 = d1.drop("Soil_Temp", axis=1)
d1 = d1.drop("Climate", axis=1)
d1 = d1.drop("Crop_Name", axis=1)
d1 = d1.drop("Season", axis=1)
d1 = d1.drop("Irrigation", axis=1)

d2 = d2.drop("Unnamed: 0", axis=1)
d2 = d2.drop("State_Name", axis=1)
d2 = d2.drop("District_Name", axis=1)
d2 = d2.drop("S_No", axis=1)
d2 = d2.drop("pH", axis=1)
d2 = d2.drop("Moisture", axis=1)
d2 = d2.drop("Soil_Temp", axis=1)
d2 = d2.drop("Climate", axis=1)
d2 = d2.drop("Crop_Name", axis=1)
d2 = d2.drop("Season", axis=1)
d2 = d2.drop("Irrigation", axis=1)

d3 = d3.drop("Unnamed: 0", axis=1)
d3 = d3.drop("State_Name", axis=1)
d3 = d3.drop("District_Name", axis=1)
d3 = d3.drop("S_No", axis=1)
d3 = d3.drop("pH", axis=1)
d3 = d3.drop("Moisture", axis=1)
d3 = d3.drop("Soil_Temp", axis=1)
d3 = d3.drop("Climate", axis=1)
d3 = d3.drop("Crop_Name", axis=1)
d3 = d3.drop("Season", axis=1)
d3 = d3.drop("Irrigation", axis=1)

d4 = d4.drop("Unnamed: 0", axis=1)
d4 = d4.drop("State_Name", axis=1)
d4 = d4.drop("District_Name", axis=1)
d4 = d4.drop("S_No", axis=1)
d4 = d4.drop("pH", axis=1)
d4 = d4.drop("Moisture", axis=1)
d4 = d4.drop("Soil_Temp", axis=1)
d4 = d4.drop("Climate", axis=1)
d4 = d4.drop("Crop_Name", axis=1)
d4 = d4.drop("Season", axis=1)
d4 = d4.drop("Irrigation", axis=1)

d5 = d5.drop("Unnamed: 0", axis=1)
d5 = d5.drop("State_Name", axis=1)
d5 = d5.drop("District_Name", axis=1)
d5 = d5.drop("S_No", axis=1)
d5 = d5.drop("pH", axis=1)
d5 = d5.drop("Moisture", axis=1)
d5 = d5.drop("Soil_Temp", axis=1)
d5 = d5.drop("Climate", axis=1)
d5 = d5.drop("Crop_Name", axis=1)
d5 = d5.drop("Season", axis=1)
d5 = d5.drop("Irrigation", axis=1)

d6 = d6.drop("Unnamed: 0", axis=1)
d6 = d6.drop("State_Name", axis=1)
d6 = d6.drop("District_Name", axis=1)
d6 = d6.drop("S_No", axis=1)
d6 = d6.drop("pH", axis=1)
d6 = d6.drop("Moisture", axis=1)
d6 = d6.drop("Soil_Temp", axis=1)
d6 = d6.drop("Climate", axis=1)
d6 = d6.drop("Crop_Name", axis=1)
d6 = d6.drop("Season", axis=1)
d6 = d6.drop("Irrigation", axis=1)

,Area,Production,UREA,DAP,MAP,MOP,NPK,TSP,Labour_hours,Yield,Rainfall
0,292000,879000.0,0.19,1.00,1,0.46,1.0,1,419.7,3010.273973,649
1,305000,878000.0,0.19,1.00,1,0.46,1.0,1,419.7,2878.688525,649
2,319000,991000.0,0.19,1.00,1,0.46,1.0,1,419.7,3106.583072,649
3,319000,972000.0,0.19,1.00,1,0.46,1.0,1,419.7,3047.021944,649
4,319000,958000.0,0.19,1.00,1,0.46,1.0,1,419.7,3003.134796,649
5,311000,879000.0,0.19,1.00,1,0.46,1.0,1,419.7,2826.366559,649
6,326000,872000.0,0.19,1.00,1,0.46,1.0,1,419.7,2674.846626,649
7,334000,1034000.0,0.19,1.00,1,0.46,1.0,1,419.7,3095.808383,649
8,345000,1003000.0,0.19,1.00,1,0.46,1.0,1,419.7,2907.246377,649
9,178000,538000.0,0.19,1.00,1,0.46,1.0,1,419.7,3022.471910,649
10,178000,546000.0,0.19,1.00,1,0.46,1.0,1,419.7,3067.415730,649
11,183000,532000.0,0.19,1.00,1,0.46,1.0,1,419.7,2907.103825,649
12,185000,501000.0,0.19,1.00,1,0.46,1.0,1,419.7,2708.108108,649
13,186000,503000.0,0.19,1.00,1,0.46,1.0,1,419.7,2704.301075,649
14,184000,482000.0,0.19,1.00,1,0.46,1.0,1,419.7,2619.565217,649
15,185000,544000.0,0.19,1.00,1,0.46,1.0,1,419.7,2940.540541,649
16,182000,518000.0,0.19,1.00,1,0.46,1.0,1,419.7,2846.153846,649
17,182000,505000.0,0.19,1.00,1,0.46,1.0,1,419.7,2774.725275,649
18,99000,466000.0,0.19,1.00,1,0.46,1.0,1,419.7,4707.070707,649
19,102000,485000.0,0.19,1.00,1,0.46,1.0,1,419.7,4754.901961,649
20,104000,496000.0,0.19,1.00,1,0.46,1.0,1,419.7,4769.230769,649
21,105000,465000.0,0.19,1.00,1,0.46,1.0,1,419.7,4428.571429,649
22,105000,459000.0,0.19,1.00,1,0.46,1.0,1,419.7,4371.428571,649
23,106000,490000.0,0.19,1.00,1,0.46,1.0,1,419.7,4622.641509,649
24,107000,500000.0,0.19,1.00,1,0.46,1.0,1,419.7,4672.897196,649
25,108000,507000.0,0.19,1.00,1,0.46,1.0,1,419.7,4694.444444,649
26,53000,212000.0,0.19,1.00,1,0.46,1.0,1,419.7,4000.000000,649
27,84000,287000.0,0.19,1.00,1,0.46,1.0,1,419.7,3416.666667,649
28,99000,392000.0,0.19,1.00,1,0.46,1.0,1,419.7,3959.595960,649
29,99000,350000.0,0.19,1.00,1,0.46,1.0,1,419.7,3535.353535,649
...,...,...,...,...,...,...,...,...,...,...,...
3003,6,10.0,1.00,0.49,1,0.34,1.0,1,859.5,1666.666667,494
3004,1,2.0,1.00,0.49,1,0.34,1.0,1,859.5,2000.000000,494
3005,1,2.0,1.00,0.49,1,0.34,1.0,1,859.5,2000.000000,494
3006,7,11.0,1.00,0.49,1,0.34,1.0,1,859.5,1571.428571,494
3007,3,6.0,1.00,0.49,1,0.34,1.0,1,859.5,2000.000000,494
3008,3,5.0,1.00,0.49,1,0.34,1.0,1,859.5,1666.666667,494
3009,33,40.0,1.00,0.49,1,0.34,1.0,1,859.5,1212.121212,494
3010,155,196.0,1.00,0.49,1,0.34,1.0,1,859.5,1264.516129,494
3011,70,66.0,1.00,0.49,1,0.34,1.0,1,859.5,942.857143,494
3012,12,15.0,1.00,0.49,1,0.34,1.0,1,859.5,1250.000000,494
3013,10,8.0,1.00,0.49,1,0.34,1.0,1,859.5,800.000000,494
3014,5,8.0,1.00,0.49,1,0.34,1.0,1,859.5,1600.000000,494
3015,5,8.0,1.00,0.49,1,0.34,1.0,1,859.5,1600.000000,494
3016,4,6.0,1.00,0.49,1,0.34,1.0,1,859.5,1500.000000,494
3017,7,11.0,1.00,0.49,1,0.34,1.0,1,859.5,1571.428571,494
3018,2,4.0,1.00,0.49,1,0.34,1.0,1,859.5,2000.000000,494
3019,10200,8700.0,1.00,0.49,1,0.34,1.0,1,859.5,852.941176,494
3020,8444,5257.0,1.00,0.49,1,0.34,1.0,1,859.5,622.572241,494
3021,6452,2877.0,1.00,0.49,1,0.34,1.0,1,859.5,445.908246,494
3022,5879,1663.0,1.00,0.49,1,0.34,1.0,1,859.5,282.871237,494
3023,6272,7038.0,1.00,0.49,1,0.34,1.0,1,859.5,1122.130102,494
3024,3683,880.0,1.00,0.49,1,0.34,1.0,1,859.5,238.935650,494
3025,5141,6070.0,1.00,0.49,1,0.34,1.0,1,859.5,1180.704143,494
3026,5564,4165.0,1.00,0.49,1,0.34,1.0,1,859.5,748.562185,494
3027,5785,4477.0,1.00,0.49,1,0.34,1.0,1,859.5,773.898012,494
3028,6175,5725.0,1.00,0.49,1,0.34,1.0,1,859.5,927.125506,494
3029,5759,4256.0,1.00,0.49,1,0.34,1.0,1,859.5,739.017190,494
3030,3689,2013.0,1.00,0.49,1,0.34,1.0,1,859.5,545.676335,494
3031,4253,2594.0,1.00,0.49,1,0.34,1.0,1,859.5,609.922408,494
3032,4881,5269.0,1.00,0.49,1,0.34,1.0,1,859.5,1079.491907,494

In [16]:
d1.to_csv("rice2.csv")
d2.to_csv("wheat2.csv")
d3.to_csv("cotton(lint)2.csv")
d4.to_csv("sugarcane2.csv")
d5.to_csv("onion2.csv")
d6.to_csv("maize2.csv")